#!/usr/bin/env ruby

require_relative 'lib/month'

# begin
case ARGV.count
  when 2
    month = ARGV[0].to_i
    year = ARGV[1].to_i
    month = Month.new(month, year)
    puts month.to_s
  when 1
    year = ARGV[0].to_i
    year = Year.new(year)
    puts year.to_s
  else
    puts "This implementation of cal requires 1 argument (month) or 2 arguments (month year)."
    exit
end
# rescue ArgumentError => e
#   e.message
# end
